class Test
    {
        public static void main(String args[]) 
        {
            int i,sum=10;
		   try 
            {
                int a;
				return ;
            }
            catch(Exception ref) 
            {
				System.out.println("catch block");        	
            } 
			finally
			{
				System.out.println("finally block");
			}
    
			System.out.println("-------------------------");
        }
    }